import os as A
B=A.path.dirname(A.path.dirname(A.path.abspath(__file__)))
C='(gmgz&heyoh0o7ullp)&v_lyv!x9^z-0g=6%e*gcy0j@q&+q#w'
D=True
E=['*']
F=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','accounts','chat']
G=['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware']
H='soMedia.urls'
I=[{'BACKEND':'django.template.backends.django.DjangoTemplates','DIRS':[A.path.join(B,'libs','templates')],'APP_DIRS':True,'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages']}}]
J='soMedia.wsgi.application'
K={'default':{'ENGINE':'django.db.backends.sqlite3','NAME':A.path.join(B,'db.sqlite3')}}
L=[{'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},{'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'},{'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'},{'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'}]
M='en-us'
N='UTC'
O=True
P=True
Q=True
R='/static/'
S=A.path.join(B,'static')
T=[A.path.join(B,'libs','static')]
U='/media/'
V=A.path.join(B,'media')
W='/'
X='/accounts/login'
Y='accounts.User'